---

- name: Download Logstash package
  become: yes
  get_url:
    dest: "/usr/local/src/logstash-{{ sansible_logstash_version }}_all.deb"
    url: "https://download.elastic.co/logstash/logstash/packages/debian/logstash-{{ sansible_logstash_version }}_all.deb"

- name: Install Logstash
  become: yes
  apt:
    deb: "/usr/local/src/logstash-{{ sansible_logstash_version }}_all.deb"
    state: present

- name: Install logstash plugins
  become: yes
  shell: "bin/plugin list {{ item }} || bin/plugin install {{ item }}"
  register: install_result
  args:
    chdir: "/opt/logstash"
  with_items: "{{ sansible_logstash_plugins }}"
  changed_when: "'Installation successful' in install_result.stdout"
  notify:
    - restart logstash

- name: Update logstash plugins
  become: yes
  command: "bin/plugin update --no-verify {{ item }}"
  args:
    chdir: "/opt/logstash"
  with_items: "{{ sansible_logstash_plugins_update }}"
  changed_when: no
  notify:
    - restart logstash
