---

- name: Add Logstash gpg key
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Logstash repo
  become: yes
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/logstash/{{ sansible_logstash_family }}/debian stable main"
    state: present

- name: Install Logstash
  become: yes
  apt:
    name: "logstash={{ sansible_logstash_version }}"

- name: Install logstash plugins
  become: yes
  shell: "bin/plugin list {{ item }} || bin/plugin install {{ item }}"
  register: install_result
  args:
    chdir: "/opt/logstash"
  with_items: "{{ sansible_logstash_plugins }}"
  changed_when: "'Installation successful' in install_result.stdout"
  notify:
    - restart logstash

- name: Update logstash plugins
  become: yes
  command: "bin/plugin update --no-verify {{ item }}"
  args:
    chdir: "/opt/logstash"
  with_items: "{{ sansible_logstash_plugins_update }}"
  changed_when: no
  notify:
    - restart logstash
