---

- name: Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https

- name: Install 2.x Family
  include: install/2.x.yml
  when: sansible_logstash_family[:1] == '2'

- name: Install 5.x Family
  include: install/5.x.yml
  when: sansible_logstash_family == '5.x'

- name: Enable logstash service
  become: yes
  service:
    name: logstash
    enabled: yes
  notify:
    - start logstash
