---

- name: Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https

- name: Install 2.x Family
  include: install/2.x.yml
  when: sansible_logstash_family[:1] == '2'

- name: Install 5.x Family
  include: install/5.x.yml
  when: sansible_logstash_family == '5.x'

- name: Ensure Logstash service is enabled for SysV
  become: yes
  service:
    enabled: yes
    name: logstash
  when: ansible_service_mgr != "systemd"

- name: Ensure Logstash service is enabled for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: logstash
  when: ansible_service_mgr == "systemd"
