---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install apt-transport-https, net-tools
      become: yes
      apt:
        name:
          - apt-transport-https
          - lsb-release
          - net-tools
        update_cache: yes

  roles:
    - role: logstash
      sansible_logstash_family: "2.4"
      sansible_logstash_version: 2.4.1
      sansible_logstash_plugins:
        - logstash-patterns-core
        - logstash-filter-prune
